In [11]:
import torch

In [14]:
a = torch.randn(4, 4)
a

tensor([[-1.3225,  1.2563, -0.0838,  0.8281],
        [ 1.6889,  0.4367, -0.3308,  0.1056],
        [ 0.0259, -1.9693,  0.9157, -0.1840],
        [ 0.7181, -0.0301,  0.2324,  0.5437]])

In [6]:
torch.argmax(a, dim=1)

tensor([0, 2, 2, 2])

In [15]:
import numpy as np
A = [1, 2, 2, 5,3, 4, 3]
a = np.unique(A)
B= (1, 2, 2,5, 3, 4, 3)
b= np.unique(B)
C= ['fgfh','asd','fgfh','asdfds','wrh']
c= np.unique(C)
print(a)
print(b)


[1 2 3 4 5]
[1 2 3 4 5]


In [17]:
a[[2,4]]

array([3, 5])